name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04']
        go_version: ['1.19', '1.20', '1.21.x']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: build
      run: sudo apt-get install docker-compose -y

    - name: Create-DB
      run: docker-compose up -d postgres

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
