name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: build
      run: sudo apt-get install docker-compose -y

    - name: Create-DB
      run: docker-compose up -d postgres

    - name: Test
      run: go test -v main_test.go 